apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/subscriptions: jace-test/test-app-subscription-1
    open-cluster-management.io/user-group: >-
      c3lzdGVtOnNlcnZpY2VhY2NvdW50cyxzeXN0ZW06c2VydmljZWFjY291bnRzOm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LHN5c3RlbTphdXRoZW50aWNhdGVk
    open-cluster-management.io/user-identity: >-
      c3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50Om11bHRpY2x1c3Rlci1hcHBsaWNhdGlvbnM=
  name: test-app
  namespace: user3
  resourceVersion: '1739788'
  uid: 7a5c0df0-267b-4c2c-8c59-489a6e5d0989
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - test-app
